# Generated by Django 4.2.5 on 2023-10-05 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Author's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Autor's description")),
            ],
        ),
        migrations.CreateModel(
            name='BookName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Book's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Book's description")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.author', verbose_name="Author's name")),
            ],
        ),
    ]
