# Generated by Django 4.2.5 on 2023-10-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_agelimit_currency_rating_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Book type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Book type description')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Payment system's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Payment system's description")),
            ],
        ),
        migrations.CreateModel(
            name='TextFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Format')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Format description')),
            ],
        ),
        migrations.AlterField(
            model_name='bookname',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Books'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Currency description'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=3, verbose_name='Currency name'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.IntegerField(verbose_name='Rating'),
        ),
    ]
