# Generated by Django 4.2.5 on 2023-10-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_booktype_paymentsystem_textformat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyrightHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Copyright holder's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Copyright holder's description")),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Genre name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Genre description')),
            ],
        ),
        migrations.AlterField(
            model_name='booktype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Book type name'),
        ),
        migrations.AlterField(
            model_name='textformat',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Format name'),
        ),
    ]
