# Generated by Django 4.2.5 on 2023-10-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_alter_bookname_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Currency descrnameiption'),
        ),
    ]
