# Generated by Django 4.2.5 on 2023-10-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0007_delete_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True, verbose_name='Currency name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Currency descrnameiption')),
            ],
        ),
    ]
