# Generated by Django 4.2.5 on 2023-10-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0008_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookname',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Book description'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Currency description'),
        ),
    ]
