# Generated by Django 4.2.5 on 2023-10-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0009_alter_bookname_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextFormat',
        ),
        migrations.AlterField(
            model_name='agelimit',
            name='name',
            field=models.CharField(max_length=3, unique=True, verbose_name='Age limit'),
        ),
        migrations.AlterField(
            model_name='booktype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Book type name'),
        ),
        migrations.AlterField(
            model_name='copyrightholder',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name="Copyright holder's name"),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Genre name'),
        ),
        migrations.AlterField(
            model_name='paymentsystem',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name="Payment system's name"),
        ),
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.IntegerField(unique=True, verbose_name='Rating'),
        ),
    ]
