# Generated by Django 4.2.5 on 2023-10-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0010_delete_textformat_alter_agelimit_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookType',
        ),
    ]
