# Generated by Django 4.2.5 on 2023-10-18 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0011_delete_booktype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentSystem',
        ),
    ]
