# Generated by Django 4.2.5 on 2023-10-18 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0012_delete_paymentsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookname',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='book_names', to='directories.genre', verbose_name='Genre name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookname',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='book_names', to='directories.series', verbose_name='Series name'),
            preserve_default=False,
        ),
    ]
