# Generated by Django 4.2.5 on 2023-10-18 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0013_bookname_genre_bookname_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookname',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookname',
            name='series',
        ),
    ]
