# Generated by Django 4.2.5 on 2023-10-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0014_remove_bookname_genre_remove_bookname_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='copyright_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_names', to='directories.copyrightholder', verbose_name='Copyright holder name'),
        ),
    ]
