# Generated by Django 4.2.5 on 2023-10-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0016_bookname_genre_bookname_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookname',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_names', to='directories.author', verbose_name='Author name'),
        ),
        migrations.AlterField(
            model_name='bookname',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Book name'),
        ),
    ]
