# Generated by Django 4.2.5 on 2023-10-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0017_alter_bookname_author_alter_bookname_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Book type name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Book type description')),
            ],
        ),
    ]
