# Generated by Django 4.2.5 on 2023-10-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0018_booktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookname',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Book price'),
        ),
    ]
