# Generated by Django 4.2.5 on 2023-10-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0023_alter_rating_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookname',
            old_name='book_type',
            new_name='booktype',
        ),
    ]
