# Generated by Django 4.2.5 on 2023-10-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0024_rename_book_type_bookname_booktype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookname',
            old_name='booktype',
            new_name='booktypename',
        ),
    ]
