# Generated by Django 4.2.5 on 2023-10-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0025_rename_booktype_bookname_booktypename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.IntegerField(max_length=3, unique=True, verbose_name='Rating value'),
        ),
    ]
