# Generated by Django 4.2.5 on 2023-10-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0027_alter_rating_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookname',
            name='booktypename',
        ),
    ]
