# Generated by Django 4.2.5 on 2023-10-26 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0029_bookname_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookname',
            name='age_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_names', to='directories.agelimit', verbose_name='Age limit value'),
        ),
    ]
