# Generated by Django 4.2.5 on 2023-10-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0030_bookname_age_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookname',
            name='book_type',
        ),
    ]
