# Generated by Django 4.2.5 on 2023-10-27 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0034_rename_booktypename_bookname_booktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookname',
            name='agelimit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_names', to='directories.agelimit', verbose_name='Age limit'),
        ),
    ]
