# Generated by Django 4.2.5 on 2023-11-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0035_bookname_agelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookname',
            name='avaliable_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
