# Generated by Django 4.2.5 on 2023-11-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0038_bookname_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookname',
            old_name='ISBN',
            new_name='isbn',
        ),
    ]
