# Generated by Django 4.2.5 on 2023-11-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0039_rename_isbn_bookname_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookname',
            name='sale_avaliability',
            field=models.BooleanField(default=True, verbose_name='Avaliability'),
        ),
    ]
