# Generated by Django 4.2.5 on 2023-11-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0040_bookname_sale_avaliability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookname',
            old_name='avaliable_quantity',
            new_name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='bookname',
            name='sale_avaliability',
        ),
        migrations.AddField(
            model_name='bookname',
            name='sale_availability',
            field=models.BooleanField(default=True, verbose_name='Availability'),
        ),
    ]
