# Generated by Django 4.2.5 on 2023-10-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0018_booktype'),
        ('applications', '0002_order_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_bookname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directories.bookname', verbose_name='Book name'),
            preserve_default=False,
        ),
    ]
