# Generated by Django 4.2.5 on 2023-10-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_order_order_bookname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('Вася-Петря', 'Vasia and Pethja')]},
        ),
    ]
