# Generated by Django 4.2.5 on 2023-10-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0018_booktype'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='orders.cart', verbose_name='Cart')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='directories.bookname', verbose_name='Good')),
            ],
        ),
    ]
