# Generated by Django 4.2.5 on 2023-10-28 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_goodincart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_adress', models.TextField(verbose_name='Delivery adress')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone_number', models.CharField(max_length=13, verbose_name='Telephone number')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.cart', verbose_name='Cart')),
            ],
        ),
    ]
