# Generated by Django 4.2.5 on 2023-10-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telephone_number',
            field=models.PositiveIntegerField(verbose_name='Telephone number'),
        ),
    ]
