# Generated by Django 4.2.5 on 2023-10-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_number', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Region's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Region's description")),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Autor's description"),
        ),
    ]
