# Generated by Django 4.2.5 on 2023-10-02 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('random_number', '0004_bookname_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookname',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='random_number.author', verbose_name="Author's name"),
        ),
    ]
