# Generated by Django 4.2.5 on 2023-10-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_number', '0005_alter_bookname_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookname',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='BookName',
        ),
    ]
